//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SGM_SaleGas.ServiceReference1 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.ServiceSoap")]
    public interface ServiceSoap {
        
        // CODEGEN: Generating message contract since element name stGasStationID from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ValidateGasStationLogin", ReplyAction="*")]
        SGM_SaleGas.ServiceReference1.ValidateGasStationLoginResponse ValidateGasStationLogin(SGM_SaleGas.ServiceReference1.ValidateGasStationLoginRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ValidateGasStationLoginRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ValidateGasStationLogin", Namespace="http://tempuri.org/", Order=0)]
        public SGM_SaleGas.ServiceReference1.ValidateGasStationLoginRequestBody Body;
        
        public ValidateGasStationLoginRequest() {
        }
        
        public ValidateGasStationLoginRequest(SGM_SaleGas.ServiceReference1.ValidateGasStationLoginRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ValidateGasStationLoginRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string stGasStationID;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string stGasStationMacAddress;
        
        public ValidateGasStationLoginRequestBody() {
        }
        
        public ValidateGasStationLoginRequestBody(string stGasStationID, string stGasStationMacAddress) {
            this.stGasStationID = stGasStationID;
            this.stGasStationMacAddress = stGasStationMacAddress;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ValidateGasStationLoginResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ValidateGasStationLoginResponse", Namespace="http://tempuri.org/", Order=0)]
        public SGM_SaleGas.ServiceReference1.ValidateGasStationLoginResponseBody Body;
        
        public ValidateGasStationLoginResponse() {
        }
        
        public ValidateGasStationLoginResponse(SGM_SaleGas.ServiceReference1.ValidateGasStationLoginResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ValidateGasStationLoginResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string ValidateGasStationLoginResult;
        
        public ValidateGasStationLoginResponseBody() {
        }
        
        public ValidateGasStationLoginResponseBody(string ValidateGasStationLoginResult) {
            this.ValidateGasStationLoginResult = ValidateGasStationLoginResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ServiceSoapChannel : SGM_SaleGas.ServiceReference1.ServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServiceSoapClient : System.ServiceModel.ClientBase<SGM_SaleGas.ServiceReference1.ServiceSoap>, SGM_SaleGas.ServiceReference1.ServiceSoap {
        
        public ServiceSoapClient() {
        }
        
        public ServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SGM_SaleGas.ServiceReference1.ValidateGasStationLoginResponse SGM_SaleGas.ServiceReference1.ServiceSoap.ValidateGasStationLogin(SGM_SaleGas.ServiceReference1.ValidateGasStationLoginRequest request) {
            return base.Channel.ValidateGasStationLogin(request);
        }
        
        public string ValidateGasStationLogin(string stGasStationID, string stGasStationMacAddress) {
            SGM_SaleGas.ServiceReference1.ValidateGasStationLoginRequest inValue = new SGM_SaleGas.ServiceReference1.ValidateGasStationLoginRequest();
            inValue.Body = new SGM_SaleGas.ServiceReference1.ValidateGasStationLoginRequestBody();
            inValue.Body.stGasStationID = stGasStationID;
            inValue.Body.stGasStationMacAddress = stGasStationMacAddress;
            SGM_SaleGas.ServiceReference1.ValidateGasStationLoginResponse retVal = ((SGM_SaleGas.ServiceReference1.ServiceSoap)(this)).ValidateGasStationLogin(inValue);
            return retVal.Body.ValidateGasStationLoginResult;
        }
    }
}
