//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SGM_SaleGas.ServiceReference1 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.ServiceSoap")]
    public interface ServiceSoap {
        
        // CODEGEN: Generating message contract since element name GASSTATION_ID from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ValidateGasStationLoginCode", ReplyAction="*")]
        SGM_SaleGas.ServiceReference1.ValidateGasStationLoginCodeResponse ValidateGasStationLoginCode(SGM_SaleGas.ServiceReference1.ValidateGasStationLoginCodeRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ValidateGasStationLoginCodeRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ValidateGasStationLoginCode", Namespace="http://tempuri.org/", Order=0)]
        public SGM_SaleGas.ServiceReference1.ValidateGasStationLoginCodeRequestBody Body;
        
        public ValidateGasStationLoginCodeRequest() {
        }
        
        public ValidateGasStationLoginCodeRequest(SGM_SaleGas.ServiceReference1.ValidateGasStationLoginCodeRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ValidateGasStationLoginCodeRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string GASSTATION_ID;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string GASSTATION_MACADDRESS;
        
        public ValidateGasStationLoginCodeRequestBody() {
        }
        
        public ValidateGasStationLoginCodeRequestBody(string GASSTATION_ID, string GASSTATION_MACADDRESS) {
            this.GASSTATION_ID = GASSTATION_ID;
            this.GASSTATION_MACADDRESS = GASSTATION_MACADDRESS;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ValidateGasStationLoginCodeResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ValidateGasStationLoginCodeResponse", Namespace="http://tempuri.org/", Order=0)]
        public SGM_SaleGas.ServiceReference1.ValidateGasStationLoginCodeResponseBody Body;
        
        public ValidateGasStationLoginCodeResponse() {
        }
        
        public ValidateGasStationLoginCodeResponse(SGM_SaleGas.ServiceReference1.ValidateGasStationLoginCodeResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ValidateGasStationLoginCodeResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string ValidateGasStationLoginCodeResult;
        
        public ValidateGasStationLoginCodeResponseBody() {
        }
        
        public ValidateGasStationLoginCodeResponseBody(string ValidateGasStationLoginCodeResult) {
            this.ValidateGasStationLoginCodeResult = ValidateGasStationLoginCodeResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ServiceSoapChannel : SGM_SaleGas.ServiceReference1.ServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServiceSoapClient : System.ServiceModel.ClientBase<SGM_SaleGas.ServiceReference1.ServiceSoap>, SGM_SaleGas.ServiceReference1.ServiceSoap {
        
        public ServiceSoapClient() {
        }
        
        public ServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SGM_SaleGas.ServiceReference1.ValidateGasStationLoginCodeResponse SGM_SaleGas.ServiceReference1.ServiceSoap.ValidateGasStationLoginCode(SGM_SaleGas.ServiceReference1.ValidateGasStationLoginCodeRequest request) {
            return base.Channel.ValidateGasStationLoginCode(request);
        }
        
        public string ValidateGasStationLoginCode(string GASSTATION_ID, string GASSTATION_MACADDRESS) {
            SGM_SaleGas.ServiceReference1.ValidateGasStationLoginCodeRequest inValue = new SGM_SaleGas.ServiceReference1.ValidateGasStationLoginCodeRequest();
            inValue.Body = new SGM_SaleGas.ServiceReference1.ValidateGasStationLoginCodeRequestBody();
            inValue.Body.GASSTATION_ID = GASSTATION_ID;
            inValue.Body.GASSTATION_MACADDRESS = GASSTATION_MACADDRESS;
            SGM_SaleGas.ServiceReference1.ValidateGasStationLoginCodeResponse retVal = ((SGM_SaleGas.ServiceReference1.ServiceSoap)(this)).ValidateGasStationLoginCode(inValue);
            return retVal.Body.ValidateGasStationLoginCodeResult;
        }
    }
}
