//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SGM_Management.SGM_Service {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="SGM_Service.ServiceSoap")]
    public interface ServiceSoap {
        
        // CODEGEN: Generating message contract since element name stGasStationID from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SGMSaleGas_ValidateGasStationLogin", ReplyAction="*")]
        SGM_Management.SGM_Service.SGMSaleGas_ValidateGasStationLoginResponse SGMSaleGas_ValidateGasStationLogin(SGM_Management.SGM_Service.SGMSaleGas_ValidateGasStationLoginRequest request);
        
        // CODEGEN: Generating message contract since element name strCardId from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SGMSaleGas_ValidateCardId", ReplyAction="*")]
        SGM_Management.SGM_Service.SGMSaleGas_ValidateCardIdResponse SGMSaleGas_ValidateCardId(SGM_Management.SGM_Service.SGMSaleGas_ValidateCardIdRequest request);
        
        // CODEGEN: Generating message contract since element name strCardId from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SGMSaleGas_GasBuying", ReplyAction="*")]
        SGM_Management.SGM_Service.SGMSaleGas_GasBuyingResponse SGMSaleGas_GasBuying(SGM_Management.SGM_Service.SGMSaleGas_GasBuyingRequest request);
        
        // CODEGEN: Generating message contract since element name admin from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SGMManager_ValidateAdminLogin", ReplyAction="*")]
        SGM_Management.SGM_Service.SGMManager_ValidateAdminLoginResponse SGMManager_ValidateAdminLogin(SGM_Management.SGM_Service.SGMManager_ValidateAdminLoginRequest request);
        
        // CODEGEN: Generating message contract since element name admin from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SGMManager_UpdateAdminAccount", ReplyAction="*")]
        SGM_Management.SGM_Service.SGMManager_UpdateAdminAccountResponse SGMManager_UpdateAdminAccount(SGM_Management.SGM_Service.SGMManager_UpdateAdminAccountRequest request);
        
        // CODEGEN: Generating message contract since element name jsonSysAdminDTO from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SGMManager_UpdateSystemPrice", ReplyAction="*")]
        SGM_Management.SGM_Service.SGMManager_UpdateSystemPriceResponse SGMManager_UpdateSystemPrice(SGM_Management.SGM_Service.SGMManager_UpdateSystemPriceRequest request);
        
        // CODEGEN: Generating message contract since element name jsonSysAdminDTO from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SGMManager_UpdateSystemStore", ReplyAction="*")]
        SGM_Management.SGM_Service.SGMManager_UpdateSystemStoreResponse SGMManager_UpdateSystemStore(SGM_Management.SGM_Service.SGMManager_UpdateSystemStoreRequest request);
        
        // CODEGEN: Generating message contract since element name stCusID from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SGMManager_CheckCustomerExist", ReplyAction="*")]
        SGM_Management.SGM_Service.SGMManager_CheckCustomerExistResponse SGMManager_CheckCustomerExist(SGM_Management.SGM_Service.SGMManager_CheckCustomerExistRequest request);
        
        // CODEGEN: Generating message contract since element name jsonCustomerDTO from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SGMManager_AddNewCustomer", ReplyAction="*")]
        SGM_Management.SGM_Service.SGMManager_AddNewCustomerResponse SGMManager_AddNewCustomer(SGM_Management.SGM_Service.SGMManager_AddNewCustomerRequest request);
        
        // CODEGEN: Generating message contract since element name stCusID from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SGMManager_GetCustomer", ReplyAction="*")]
        SGM_Management.SGM_Service.SGMManager_GetCustomerResponse SGMManager_GetCustomer(SGM_Management.SGM_Service.SGMManager_GetCustomerRequest request);
        
        // CODEGEN: Generating message contract since element name jsonCustomerDTO from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SGMManager_UpdateCustomer", ReplyAction="*")]
        SGM_Management.SGM_Service.SGMManager_UpdateCustomerResponse SGMManager_UpdateCustomer(SGM_Management.SGM_Service.SGMManager_UpdateCustomerRequest request);
        
        // CODEGEN: Generating message contract since element name stCusID from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SGMManager_DelCustomer", ReplyAction="*")]
        SGM_Management.SGM_Service.SGMManager_DelCustomerResponse SGMManager_DelCustomer(SGM_Management.SGM_Service.SGMManager_DelCustomerRequest request);
        
        // CODEGEN: Generating message contract since element name stCardID from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SGMManager_CheckCardExist", ReplyAction="*")]
        SGM_Management.SGM_Service.SGMManager_CheckCardExistResponse SGMManager_CheckCardExist(SGM_Management.SGM_Service.SGMManager_CheckCardExistRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SGMSaleGas_ValidateGasStationLoginRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SGMSaleGas_ValidateGasStationLogin", Namespace="http://tempuri.org/", Order=0)]
        public SGM_Management.SGM_Service.SGMSaleGas_ValidateGasStationLoginRequestBody Body;
        
        public SGMSaleGas_ValidateGasStationLoginRequest() {
        }
        
        public SGMSaleGas_ValidateGasStationLoginRequest(SGM_Management.SGM_Service.SGMSaleGas_ValidateGasStationLoginRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SGMSaleGas_ValidateGasStationLoginRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string stGasStationID;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string stGasStationMacAddress;
        
        public SGMSaleGas_ValidateGasStationLoginRequestBody() {
        }
        
        public SGMSaleGas_ValidateGasStationLoginRequestBody(string stGasStationID, string stGasStationMacAddress) {
            this.stGasStationID = stGasStationID;
            this.stGasStationMacAddress = stGasStationMacAddress;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SGMSaleGas_ValidateGasStationLoginResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SGMSaleGas_ValidateGasStationLoginResponse", Namespace="http://tempuri.org/", Order=0)]
        public SGM_Management.SGM_Service.SGMSaleGas_ValidateGasStationLoginResponseBody Body;
        
        public SGMSaleGas_ValidateGasStationLoginResponse() {
        }
        
        public SGMSaleGas_ValidateGasStationLoginResponse(SGM_Management.SGM_Service.SGMSaleGas_ValidateGasStationLoginResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SGMSaleGas_ValidateGasStationLoginResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string SGMSaleGas_ValidateGasStationLoginResult;
        
        public SGMSaleGas_ValidateGasStationLoginResponseBody() {
        }
        
        public SGMSaleGas_ValidateGasStationLoginResponseBody(string SGMSaleGas_ValidateGasStationLoginResult) {
            this.SGMSaleGas_ValidateGasStationLoginResult = SGMSaleGas_ValidateGasStationLoginResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SGMSaleGas_ValidateCardIdRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SGMSaleGas_ValidateCardId", Namespace="http://tempuri.org/", Order=0)]
        public SGM_Management.SGM_Service.SGMSaleGas_ValidateCardIdRequestBody Body;
        
        public SGMSaleGas_ValidateCardIdRequest() {
        }
        
        public SGMSaleGas_ValidateCardIdRequest(SGM_Management.SGM_Service.SGMSaleGas_ValidateCardIdRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SGMSaleGas_ValidateCardIdRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string strCardId;
        
        public SGMSaleGas_ValidateCardIdRequestBody() {
        }
        
        public SGMSaleGas_ValidateCardIdRequestBody(string strCardId) {
            this.strCardId = strCardId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SGMSaleGas_ValidateCardIdResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SGMSaleGas_ValidateCardIdResponse", Namespace="http://tempuri.org/", Order=0)]
        public SGM_Management.SGM_Service.SGMSaleGas_ValidateCardIdResponseBody Body;
        
        public SGMSaleGas_ValidateCardIdResponse() {
        }
        
        public SGMSaleGas_ValidateCardIdResponse(SGM_Management.SGM_Service.SGMSaleGas_ValidateCardIdResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SGMSaleGas_ValidateCardIdResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string SGMSaleGas_ValidateCardIdResult;
        
        public SGMSaleGas_ValidateCardIdResponseBody() {
        }
        
        public SGMSaleGas_ValidateCardIdResponseBody(string SGMSaleGas_ValidateCardIdResult) {
            this.SGMSaleGas_ValidateCardIdResult = SGMSaleGas_ValidateCardIdResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SGMSaleGas_GasBuyingRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SGMSaleGas_GasBuying", Namespace="http://tempuri.org/", Order=0)]
        public SGM_Management.SGM_Service.SGMSaleGas_GasBuyingRequestBody Body;
        
        public SGMSaleGas_GasBuyingRequest() {
        }
        
        public SGMSaleGas_GasBuyingRequest(SGM_Management.SGM_Service.SGMSaleGas_GasBuyingRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SGMSaleGas_GasBuyingRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string strCardId;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public int money;
        
        public SGMSaleGas_GasBuyingRequestBody() {
        }
        
        public SGMSaleGas_GasBuyingRequestBody(string strCardId, int money) {
            this.strCardId = strCardId;
            this.money = money;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SGMSaleGas_GasBuyingResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SGMSaleGas_GasBuyingResponse", Namespace="http://tempuri.org/", Order=0)]
        public SGM_Management.SGM_Service.SGMSaleGas_GasBuyingResponseBody Body;
        
        public SGMSaleGas_GasBuyingResponse() {
        }
        
        public SGMSaleGas_GasBuyingResponse(SGM_Management.SGM_Service.SGMSaleGas_GasBuyingResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SGMSaleGas_GasBuyingResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string SGMSaleGas_GasBuyingResult;
        
        public SGMSaleGas_GasBuyingResponseBody() {
        }
        
        public SGMSaleGas_GasBuyingResponseBody(string SGMSaleGas_GasBuyingResult) {
            this.SGMSaleGas_GasBuyingResult = SGMSaleGas_GasBuyingResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SGMManager_ValidateAdminLoginRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SGMManager_ValidateAdminLogin", Namespace="http://tempuri.org/", Order=0)]
        public SGM_Management.SGM_Service.SGMManager_ValidateAdminLoginRequestBody Body;
        
        public SGMManager_ValidateAdminLoginRequest() {
        }
        
        public SGMManager_ValidateAdminLoginRequest(SGM_Management.SGM_Service.SGMManager_ValidateAdminLoginRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SGMManager_ValidateAdminLoginRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string admin;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string pwd;
        
        public SGMManager_ValidateAdminLoginRequestBody() {
        }
        
        public SGMManager_ValidateAdminLoginRequestBody(string admin, string pwd) {
            this.admin = admin;
            this.pwd = pwd;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SGMManager_ValidateAdminLoginResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SGMManager_ValidateAdminLoginResponse", Namespace="http://tempuri.org/", Order=0)]
        public SGM_Management.SGM_Service.SGMManager_ValidateAdminLoginResponseBody Body;
        
        public SGMManager_ValidateAdminLoginResponse() {
        }
        
        public SGMManager_ValidateAdminLoginResponse(SGM_Management.SGM_Service.SGMManager_ValidateAdminLoginResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SGMManager_ValidateAdminLoginResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string SGMManager_ValidateAdminLoginResult;
        
        public SGMManager_ValidateAdminLoginResponseBody() {
        }
        
        public SGMManager_ValidateAdminLoginResponseBody(string SGMManager_ValidateAdminLoginResult) {
            this.SGMManager_ValidateAdminLoginResult = SGMManager_ValidateAdminLoginResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SGMManager_UpdateAdminAccountRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SGMManager_UpdateAdminAccount", Namespace="http://tempuri.org/", Order=0)]
        public SGM_Management.SGM_Service.SGMManager_UpdateAdminAccountRequestBody Body;
        
        public SGMManager_UpdateAdminAccountRequest() {
        }
        
        public SGMManager_UpdateAdminAccountRequest(SGM_Management.SGM_Service.SGMManager_UpdateAdminAccountRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SGMManager_UpdateAdminAccountRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string admin;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string admin_new;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string pwd;
        
        public SGMManager_UpdateAdminAccountRequestBody() {
        }
        
        public SGMManager_UpdateAdminAccountRequestBody(string admin, string admin_new, string pwd) {
            this.admin = admin;
            this.admin_new = admin_new;
            this.pwd = pwd;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SGMManager_UpdateAdminAccountResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SGMManager_UpdateAdminAccountResponse", Namespace="http://tempuri.org/", Order=0)]
        public SGM_Management.SGM_Service.SGMManager_UpdateAdminAccountResponseBody Body;
        
        public SGMManager_UpdateAdminAccountResponse() {
        }
        
        public SGMManager_UpdateAdminAccountResponse(SGM_Management.SGM_Service.SGMManager_UpdateAdminAccountResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SGMManager_UpdateAdminAccountResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string SGMManager_UpdateAdminAccountResult;
        
        public SGMManager_UpdateAdminAccountResponseBody() {
        }
        
        public SGMManager_UpdateAdminAccountResponseBody(string SGMManager_UpdateAdminAccountResult) {
            this.SGMManager_UpdateAdminAccountResult = SGMManager_UpdateAdminAccountResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SGMManager_UpdateSystemPriceRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SGMManager_UpdateSystemPrice", Namespace="http://tempuri.org/", Order=0)]
        public SGM_Management.SGM_Service.SGMManager_UpdateSystemPriceRequestBody Body;
        
        public SGMManager_UpdateSystemPriceRequest() {
        }
        
        public SGMManager_UpdateSystemPriceRequest(SGM_Management.SGM_Service.SGMManager_UpdateSystemPriceRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SGMManager_UpdateSystemPriceRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string jsonSysAdminDTO;
        
        public SGMManager_UpdateSystemPriceRequestBody() {
        }
        
        public SGMManager_UpdateSystemPriceRequestBody(string jsonSysAdminDTO) {
            this.jsonSysAdminDTO = jsonSysAdminDTO;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SGMManager_UpdateSystemPriceResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SGMManager_UpdateSystemPriceResponse", Namespace="http://tempuri.org/", Order=0)]
        public SGM_Management.SGM_Service.SGMManager_UpdateSystemPriceResponseBody Body;
        
        public SGMManager_UpdateSystemPriceResponse() {
        }
        
        public SGMManager_UpdateSystemPriceResponse(SGM_Management.SGM_Service.SGMManager_UpdateSystemPriceResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SGMManager_UpdateSystemPriceResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string SGMManager_UpdateSystemPriceResult;
        
        public SGMManager_UpdateSystemPriceResponseBody() {
        }
        
        public SGMManager_UpdateSystemPriceResponseBody(string SGMManager_UpdateSystemPriceResult) {
            this.SGMManager_UpdateSystemPriceResult = SGMManager_UpdateSystemPriceResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SGMManager_UpdateSystemStoreRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SGMManager_UpdateSystemStore", Namespace="http://tempuri.org/", Order=0)]
        public SGM_Management.SGM_Service.SGMManager_UpdateSystemStoreRequestBody Body;
        
        public SGMManager_UpdateSystemStoreRequest() {
        }
        
        public SGMManager_UpdateSystemStoreRequest(SGM_Management.SGM_Service.SGMManager_UpdateSystemStoreRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SGMManager_UpdateSystemStoreRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string jsonSysAdminDTO;
        
        public SGMManager_UpdateSystemStoreRequestBody() {
        }
        
        public SGMManager_UpdateSystemStoreRequestBody(string jsonSysAdminDTO) {
            this.jsonSysAdminDTO = jsonSysAdminDTO;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SGMManager_UpdateSystemStoreResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SGMManager_UpdateSystemStoreResponse", Namespace="http://tempuri.org/", Order=0)]
        public SGM_Management.SGM_Service.SGMManager_UpdateSystemStoreResponseBody Body;
        
        public SGMManager_UpdateSystemStoreResponse() {
        }
        
        public SGMManager_UpdateSystemStoreResponse(SGM_Management.SGM_Service.SGMManager_UpdateSystemStoreResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SGMManager_UpdateSystemStoreResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string SGMManager_UpdateSystemStoreResult;
        
        public SGMManager_UpdateSystemStoreResponseBody() {
        }
        
        public SGMManager_UpdateSystemStoreResponseBody(string SGMManager_UpdateSystemStoreResult) {
            this.SGMManager_UpdateSystemStoreResult = SGMManager_UpdateSystemStoreResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SGMManager_CheckCustomerExistRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SGMManager_CheckCustomerExist", Namespace="http://tempuri.org/", Order=0)]
        public SGM_Management.SGM_Service.SGMManager_CheckCustomerExistRequestBody Body;
        
        public SGMManager_CheckCustomerExistRequest() {
        }
        
        public SGMManager_CheckCustomerExistRequest(SGM_Management.SGM_Service.SGMManager_CheckCustomerExistRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SGMManager_CheckCustomerExistRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string stCusID;
        
        public SGMManager_CheckCustomerExistRequestBody() {
        }
        
        public SGMManager_CheckCustomerExistRequestBody(string stCusID) {
            this.stCusID = stCusID;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SGMManager_CheckCustomerExistResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SGMManager_CheckCustomerExistResponse", Namespace="http://tempuri.org/", Order=0)]
        public SGM_Management.SGM_Service.SGMManager_CheckCustomerExistResponseBody Body;
        
        public SGMManager_CheckCustomerExistResponse() {
        }
        
        public SGMManager_CheckCustomerExistResponse(SGM_Management.SGM_Service.SGMManager_CheckCustomerExistResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SGMManager_CheckCustomerExistResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string SGMManager_CheckCustomerExistResult;
        
        public SGMManager_CheckCustomerExistResponseBody() {
        }
        
        public SGMManager_CheckCustomerExistResponseBody(string SGMManager_CheckCustomerExistResult) {
            this.SGMManager_CheckCustomerExistResult = SGMManager_CheckCustomerExistResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SGMManager_AddNewCustomerRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SGMManager_AddNewCustomer", Namespace="http://tempuri.org/", Order=0)]
        public SGM_Management.SGM_Service.SGMManager_AddNewCustomerRequestBody Body;
        
        public SGMManager_AddNewCustomerRequest() {
        }
        
        public SGMManager_AddNewCustomerRequest(SGM_Management.SGM_Service.SGMManager_AddNewCustomerRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SGMManager_AddNewCustomerRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string jsonCustomerDTO;
        
        public SGMManager_AddNewCustomerRequestBody() {
        }
        
        public SGMManager_AddNewCustomerRequestBody(string jsonCustomerDTO) {
            this.jsonCustomerDTO = jsonCustomerDTO;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SGMManager_AddNewCustomerResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SGMManager_AddNewCustomerResponse", Namespace="http://tempuri.org/", Order=0)]
        public SGM_Management.SGM_Service.SGMManager_AddNewCustomerResponseBody Body;
        
        public SGMManager_AddNewCustomerResponse() {
        }
        
        public SGMManager_AddNewCustomerResponse(SGM_Management.SGM_Service.SGMManager_AddNewCustomerResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SGMManager_AddNewCustomerResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string SGMManager_AddNewCustomerResult;
        
        public SGMManager_AddNewCustomerResponseBody() {
        }
        
        public SGMManager_AddNewCustomerResponseBody(string SGMManager_AddNewCustomerResult) {
            this.SGMManager_AddNewCustomerResult = SGMManager_AddNewCustomerResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SGMManager_GetCustomerRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SGMManager_GetCustomer", Namespace="http://tempuri.org/", Order=0)]
        public SGM_Management.SGM_Service.SGMManager_GetCustomerRequestBody Body;
        
        public SGMManager_GetCustomerRequest() {
        }
        
        public SGMManager_GetCustomerRequest(SGM_Management.SGM_Service.SGMManager_GetCustomerRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SGMManager_GetCustomerRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string stCusID;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public bool bExactly;
        
        public SGMManager_GetCustomerRequestBody() {
        }
        
        public SGMManager_GetCustomerRequestBody(string stCusID, bool bExactly) {
            this.stCusID = stCusID;
            this.bExactly = bExactly;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SGMManager_GetCustomerResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SGMManager_GetCustomerResponse", Namespace="http://tempuri.org/", Order=0)]
        public SGM_Management.SGM_Service.SGMManager_GetCustomerResponseBody Body;
        
        public SGMManager_GetCustomerResponse() {
        }
        
        public SGMManager_GetCustomerResponse(SGM_Management.SGM_Service.SGMManager_GetCustomerResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SGMManager_GetCustomerResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string SGMManager_GetCustomerResult;
        
        public SGMManager_GetCustomerResponseBody() {
        }
        
        public SGMManager_GetCustomerResponseBody(string SGMManager_GetCustomerResult) {
            this.SGMManager_GetCustomerResult = SGMManager_GetCustomerResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SGMManager_UpdateCustomerRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SGMManager_UpdateCustomer", Namespace="http://tempuri.org/", Order=0)]
        public SGM_Management.SGM_Service.SGMManager_UpdateCustomerRequestBody Body;
        
        public SGMManager_UpdateCustomerRequest() {
        }
        
        public SGMManager_UpdateCustomerRequest(SGM_Management.SGM_Service.SGMManager_UpdateCustomerRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SGMManager_UpdateCustomerRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string jsonCustomerDTO;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string stCusID;
        
        public SGMManager_UpdateCustomerRequestBody() {
        }
        
        public SGMManager_UpdateCustomerRequestBody(string jsonCustomerDTO, string stCusID) {
            this.jsonCustomerDTO = jsonCustomerDTO;
            this.stCusID = stCusID;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SGMManager_UpdateCustomerResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SGMManager_UpdateCustomerResponse", Namespace="http://tempuri.org/", Order=0)]
        public SGM_Management.SGM_Service.SGMManager_UpdateCustomerResponseBody Body;
        
        public SGMManager_UpdateCustomerResponse() {
        }
        
        public SGMManager_UpdateCustomerResponse(SGM_Management.SGM_Service.SGMManager_UpdateCustomerResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SGMManager_UpdateCustomerResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string SGMManager_UpdateCustomerResult;
        
        public SGMManager_UpdateCustomerResponseBody() {
        }
        
        public SGMManager_UpdateCustomerResponseBody(string SGMManager_UpdateCustomerResult) {
            this.SGMManager_UpdateCustomerResult = SGMManager_UpdateCustomerResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SGMManager_DelCustomerRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SGMManager_DelCustomer", Namespace="http://tempuri.org/", Order=0)]
        public SGM_Management.SGM_Service.SGMManager_DelCustomerRequestBody Body;
        
        public SGMManager_DelCustomerRequest() {
        }
        
        public SGMManager_DelCustomerRequest(SGM_Management.SGM_Service.SGMManager_DelCustomerRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SGMManager_DelCustomerRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string stCusID;
        
        public SGMManager_DelCustomerRequestBody() {
        }
        
        public SGMManager_DelCustomerRequestBody(string stCusID) {
            this.stCusID = stCusID;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SGMManager_DelCustomerResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SGMManager_DelCustomerResponse", Namespace="http://tempuri.org/", Order=0)]
        public SGM_Management.SGM_Service.SGMManager_DelCustomerResponseBody Body;
        
        public SGMManager_DelCustomerResponse() {
        }
        
        public SGMManager_DelCustomerResponse(SGM_Management.SGM_Service.SGMManager_DelCustomerResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SGMManager_DelCustomerResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string SGMManager_DelCustomerResult;
        
        public SGMManager_DelCustomerResponseBody() {
        }
        
        public SGMManager_DelCustomerResponseBody(string SGMManager_DelCustomerResult) {
            this.SGMManager_DelCustomerResult = SGMManager_DelCustomerResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SGMManager_CheckCardExistRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SGMManager_CheckCardExist", Namespace="http://tempuri.org/", Order=0)]
        public SGM_Management.SGM_Service.SGMManager_CheckCardExistRequestBody Body;
        
        public SGMManager_CheckCardExistRequest() {
        }
        
        public SGMManager_CheckCardExistRequest(SGM_Management.SGM_Service.SGMManager_CheckCardExistRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SGMManager_CheckCardExistRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string stCardID;
        
        public SGMManager_CheckCardExistRequestBody() {
        }
        
        public SGMManager_CheckCardExistRequestBody(string stCardID) {
            this.stCardID = stCardID;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SGMManager_CheckCardExistResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SGMManager_CheckCardExistResponse", Namespace="http://tempuri.org/", Order=0)]
        public SGM_Management.SGM_Service.SGMManager_CheckCardExistResponseBody Body;
        
        public SGMManager_CheckCardExistResponse() {
        }
        
        public SGMManager_CheckCardExistResponse(SGM_Management.SGM_Service.SGMManager_CheckCardExistResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SGMManager_CheckCardExistResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string SGMManager_CheckCardExistResult;
        
        public SGMManager_CheckCardExistResponseBody() {
        }
        
        public SGMManager_CheckCardExistResponseBody(string SGMManager_CheckCardExistResult) {
            this.SGMManager_CheckCardExistResult = SGMManager_CheckCardExistResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ServiceSoapChannel : SGM_Management.SGM_Service.ServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServiceSoapClient : System.ServiceModel.ClientBase<SGM_Management.SGM_Service.ServiceSoap>, SGM_Management.SGM_Service.ServiceSoap {
        
        public ServiceSoapClient() {
        }
        
        public ServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SGM_Management.SGM_Service.SGMSaleGas_ValidateGasStationLoginResponse SGM_Management.SGM_Service.ServiceSoap.SGMSaleGas_ValidateGasStationLogin(SGM_Management.SGM_Service.SGMSaleGas_ValidateGasStationLoginRequest request) {
            return base.Channel.SGMSaleGas_ValidateGasStationLogin(request);
        }
        
        public string SGMSaleGas_ValidateGasStationLogin(string stGasStationID, string stGasStationMacAddress) {
            SGM_Management.SGM_Service.SGMSaleGas_ValidateGasStationLoginRequest inValue = new SGM_Management.SGM_Service.SGMSaleGas_ValidateGasStationLoginRequest();
            inValue.Body = new SGM_Management.SGM_Service.SGMSaleGas_ValidateGasStationLoginRequestBody();
            inValue.Body.stGasStationID = stGasStationID;
            inValue.Body.stGasStationMacAddress = stGasStationMacAddress;
            SGM_Management.SGM_Service.SGMSaleGas_ValidateGasStationLoginResponse retVal = ((SGM_Management.SGM_Service.ServiceSoap)(this)).SGMSaleGas_ValidateGasStationLogin(inValue);
            return retVal.Body.SGMSaleGas_ValidateGasStationLoginResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SGM_Management.SGM_Service.SGMSaleGas_ValidateCardIdResponse SGM_Management.SGM_Service.ServiceSoap.SGMSaleGas_ValidateCardId(SGM_Management.SGM_Service.SGMSaleGas_ValidateCardIdRequest request) {
            return base.Channel.SGMSaleGas_ValidateCardId(request);
        }
        
        public string SGMSaleGas_ValidateCardId(string strCardId) {
            SGM_Management.SGM_Service.SGMSaleGas_ValidateCardIdRequest inValue = new SGM_Management.SGM_Service.SGMSaleGas_ValidateCardIdRequest();
            inValue.Body = new SGM_Management.SGM_Service.SGMSaleGas_ValidateCardIdRequestBody();
            inValue.Body.strCardId = strCardId;
            SGM_Management.SGM_Service.SGMSaleGas_ValidateCardIdResponse retVal = ((SGM_Management.SGM_Service.ServiceSoap)(this)).SGMSaleGas_ValidateCardId(inValue);
            return retVal.Body.SGMSaleGas_ValidateCardIdResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SGM_Management.SGM_Service.SGMSaleGas_GasBuyingResponse SGM_Management.SGM_Service.ServiceSoap.SGMSaleGas_GasBuying(SGM_Management.SGM_Service.SGMSaleGas_GasBuyingRequest request) {
            return base.Channel.SGMSaleGas_GasBuying(request);
        }
        
        public string SGMSaleGas_GasBuying(string strCardId, int money) {
            SGM_Management.SGM_Service.SGMSaleGas_GasBuyingRequest inValue = new SGM_Management.SGM_Service.SGMSaleGas_GasBuyingRequest();
            inValue.Body = new SGM_Management.SGM_Service.SGMSaleGas_GasBuyingRequestBody();
            inValue.Body.strCardId = strCardId;
            inValue.Body.money = money;
            SGM_Management.SGM_Service.SGMSaleGas_GasBuyingResponse retVal = ((SGM_Management.SGM_Service.ServiceSoap)(this)).SGMSaleGas_GasBuying(inValue);
            return retVal.Body.SGMSaleGas_GasBuyingResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SGM_Management.SGM_Service.SGMManager_ValidateAdminLoginResponse SGM_Management.SGM_Service.ServiceSoap.SGMManager_ValidateAdminLogin(SGM_Management.SGM_Service.SGMManager_ValidateAdminLoginRequest request) {
            return base.Channel.SGMManager_ValidateAdminLogin(request);
        }
        
        public string SGMManager_ValidateAdminLogin(string admin, string pwd) {
            SGM_Management.SGM_Service.SGMManager_ValidateAdminLoginRequest inValue = new SGM_Management.SGM_Service.SGMManager_ValidateAdminLoginRequest();
            inValue.Body = new SGM_Management.SGM_Service.SGMManager_ValidateAdminLoginRequestBody();
            inValue.Body.admin = admin;
            inValue.Body.pwd = pwd;
            SGM_Management.SGM_Service.SGMManager_ValidateAdminLoginResponse retVal = ((SGM_Management.SGM_Service.ServiceSoap)(this)).SGMManager_ValidateAdminLogin(inValue);
            return retVal.Body.SGMManager_ValidateAdminLoginResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SGM_Management.SGM_Service.SGMManager_UpdateAdminAccountResponse SGM_Management.SGM_Service.ServiceSoap.SGMManager_UpdateAdminAccount(SGM_Management.SGM_Service.SGMManager_UpdateAdminAccountRequest request) {
            return base.Channel.SGMManager_UpdateAdminAccount(request);
        }
        
        public string SGMManager_UpdateAdminAccount(string admin, string admin_new, string pwd) {
            SGM_Management.SGM_Service.SGMManager_UpdateAdminAccountRequest inValue = new SGM_Management.SGM_Service.SGMManager_UpdateAdminAccountRequest();
            inValue.Body = new SGM_Management.SGM_Service.SGMManager_UpdateAdminAccountRequestBody();
            inValue.Body.admin = admin;
            inValue.Body.admin_new = admin_new;
            inValue.Body.pwd = pwd;
            SGM_Management.SGM_Service.SGMManager_UpdateAdminAccountResponse retVal = ((SGM_Management.SGM_Service.ServiceSoap)(this)).SGMManager_UpdateAdminAccount(inValue);
            return retVal.Body.SGMManager_UpdateAdminAccountResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SGM_Management.SGM_Service.SGMManager_UpdateSystemPriceResponse SGM_Management.SGM_Service.ServiceSoap.SGMManager_UpdateSystemPrice(SGM_Management.SGM_Service.SGMManager_UpdateSystemPriceRequest request) {
            return base.Channel.SGMManager_UpdateSystemPrice(request);
        }
        
        public string SGMManager_UpdateSystemPrice(string jsonSysAdminDTO) {
            SGM_Management.SGM_Service.SGMManager_UpdateSystemPriceRequest inValue = new SGM_Management.SGM_Service.SGMManager_UpdateSystemPriceRequest();
            inValue.Body = new SGM_Management.SGM_Service.SGMManager_UpdateSystemPriceRequestBody();
            inValue.Body.jsonSysAdminDTO = jsonSysAdminDTO;
            SGM_Management.SGM_Service.SGMManager_UpdateSystemPriceResponse retVal = ((SGM_Management.SGM_Service.ServiceSoap)(this)).SGMManager_UpdateSystemPrice(inValue);
            return retVal.Body.SGMManager_UpdateSystemPriceResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SGM_Management.SGM_Service.SGMManager_UpdateSystemStoreResponse SGM_Management.SGM_Service.ServiceSoap.SGMManager_UpdateSystemStore(SGM_Management.SGM_Service.SGMManager_UpdateSystemStoreRequest request) {
            return base.Channel.SGMManager_UpdateSystemStore(request);
        }
        
        public string SGMManager_UpdateSystemStore(string jsonSysAdminDTO) {
            SGM_Management.SGM_Service.SGMManager_UpdateSystemStoreRequest inValue = new SGM_Management.SGM_Service.SGMManager_UpdateSystemStoreRequest();
            inValue.Body = new SGM_Management.SGM_Service.SGMManager_UpdateSystemStoreRequestBody();
            inValue.Body.jsonSysAdminDTO = jsonSysAdminDTO;
            SGM_Management.SGM_Service.SGMManager_UpdateSystemStoreResponse retVal = ((SGM_Management.SGM_Service.ServiceSoap)(this)).SGMManager_UpdateSystemStore(inValue);
            return retVal.Body.SGMManager_UpdateSystemStoreResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SGM_Management.SGM_Service.SGMManager_CheckCustomerExistResponse SGM_Management.SGM_Service.ServiceSoap.SGMManager_CheckCustomerExist(SGM_Management.SGM_Service.SGMManager_CheckCustomerExistRequest request) {
            return base.Channel.SGMManager_CheckCustomerExist(request);
        }
        
        public string SGMManager_CheckCustomerExist(string stCusID) {
            SGM_Management.SGM_Service.SGMManager_CheckCustomerExistRequest inValue = new SGM_Management.SGM_Service.SGMManager_CheckCustomerExistRequest();
            inValue.Body = new SGM_Management.SGM_Service.SGMManager_CheckCustomerExistRequestBody();
            inValue.Body.stCusID = stCusID;
            SGM_Management.SGM_Service.SGMManager_CheckCustomerExistResponse retVal = ((SGM_Management.SGM_Service.ServiceSoap)(this)).SGMManager_CheckCustomerExist(inValue);
            return retVal.Body.SGMManager_CheckCustomerExistResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SGM_Management.SGM_Service.SGMManager_AddNewCustomerResponse SGM_Management.SGM_Service.ServiceSoap.SGMManager_AddNewCustomer(SGM_Management.SGM_Service.SGMManager_AddNewCustomerRequest request) {
            return base.Channel.SGMManager_AddNewCustomer(request);
        }
        
        public string SGMManager_AddNewCustomer(string jsonCustomerDTO) {
            SGM_Management.SGM_Service.SGMManager_AddNewCustomerRequest inValue = new SGM_Management.SGM_Service.SGMManager_AddNewCustomerRequest();
            inValue.Body = new SGM_Management.SGM_Service.SGMManager_AddNewCustomerRequestBody();
            inValue.Body.jsonCustomerDTO = jsonCustomerDTO;
            SGM_Management.SGM_Service.SGMManager_AddNewCustomerResponse retVal = ((SGM_Management.SGM_Service.ServiceSoap)(this)).SGMManager_AddNewCustomer(inValue);
            return retVal.Body.SGMManager_AddNewCustomerResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SGM_Management.SGM_Service.SGMManager_GetCustomerResponse SGM_Management.SGM_Service.ServiceSoap.SGMManager_GetCustomer(SGM_Management.SGM_Service.SGMManager_GetCustomerRequest request) {
            return base.Channel.SGMManager_GetCustomer(request);
        }
        
        public string SGMManager_GetCustomer(string stCusID, bool bExactly) {
            SGM_Management.SGM_Service.SGMManager_GetCustomerRequest inValue = new SGM_Management.SGM_Service.SGMManager_GetCustomerRequest();
            inValue.Body = new SGM_Management.SGM_Service.SGMManager_GetCustomerRequestBody();
            inValue.Body.stCusID = stCusID;
            inValue.Body.bExactly = bExactly;
            SGM_Management.SGM_Service.SGMManager_GetCustomerResponse retVal = ((SGM_Management.SGM_Service.ServiceSoap)(this)).SGMManager_GetCustomer(inValue);
            return retVal.Body.SGMManager_GetCustomerResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SGM_Management.SGM_Service.SGMManager_UpdateCustomerResponse SGM_Management.SGM_Service.ServiceSoap.SGMManager_UpdateCustomer(SGM_Management.SGM_Service.SGMManager_UpdateCustomerRequest request) {
            return base.Channel.SGMManager_UpdateCustomer(request);
        }
        
        public string SGMManager_UpdateCustomer(string jsonCustomerDTO, string stCusID) {
            SGM_Management.SGM_Service.SGMManager_UpdateCustomerRequest inValue = new SGM_Management.SGM_Service.SGMManager_UpdateCustomerRequest();
            inValue.Body = new SGM_Management.SGM_Service.SGMManager_UpdateCustomerRequestBody();
            inValue.Body.jsonCustomerDTO = jsonCustomerDTO;
            inValue.Body.stCusID = stCusID;
            SGM_Management.SGM_Service.SGMManager_UpdateCustomerResponse retVal = ((SGM_Management.SGM_Service.ServiceSoap)(this)).SGMManager_UpdateCustomer(inValue);
            return retVal.Body.SGMManager_UpdateCustomerResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SGM_Management.SGM_Service.SGMManager_DelCustomerResponse SGM_Management.SGM_Service.ServiceSoap.SGMManager_DelCustomer(SGM_Management.SGM_Service.SGMManager_DelCustomerRequest request) {
            return base.Channel.SGMManager_DelCustomer(request);
        }
        
        public string SGMManager_DelCustomer(string stCusID) {
            SGM_Management.SGM_Service.SGMManager_DelCustomerRequest inValue = new SGM_Management.SGM_Service.SGMManager_DelCustomerRequest();
            inValue.Body = new SGM_Management.SGM_Service.SGMManager_DelCustomerRequestBody();
            inValue.Body.stCusID = stCusID;
            SGM_Management.SGM_Service.SGMManager_DelCustomerResponse retVal = ((SGM_Management.SGM_Service.ServiceSoap)(this)).SGMManager_DelCustomer(inValue);
            return retVal.Body.SGMManager_DelCustomerResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SGM_Management.SGM_Service.SGMManager_CheckCardExistResponse SGM_Management.SGM_Service.ServiceSoap.SGMManager_CheckCardExist(SGM_Management.SGM_Service.SGMManager_CheckCardExistRequest request) {
            return base.Channel.SGMManager_CheckCardExist(request);
        }
        
        public string SGMManager_CheckCardExist(string stCardID) {
            SGM_Management.SGM_Service.SGMManager_CheckCardExistRequest inValue = new SGM_Management.SGM_Service.SGMManager_CheckCardExistRequest();
            inValue.Body = new SGM_Management.SGM_Service.SGMManager_CheckCardExistRequestBody();
            inValue.Body.stCardID = stCardID;
            SGM_Management.SGM_Service.SGMManager_CheckCardExistResponse retVal = ((SGM_Management.SGM_Service.ServiceSoap)(this)).SGMManager_CheckCardExist(inValue);
            return retVal.Body.SGMManager_CheckCardExistResult;
        }
    }
}
