//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SGM_SaleGas.SGM_Service {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="SGM_Service.ServiceSoap")]
    public interface ServiceSoap {
        
        // CODEGEN: Generating message contract since element name stGasStationID from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ValidateGasStationLogin", ReplyAction="*")]
        SGM_SaleGas.SGM_Service.ValidateGasStationLoginResponse ValidateGasStationLogin(SGM_SaleGas.SGM_Service.ValidateGasStationLoginRequest request);
        
        // CODEGEN: Generating message contract since element name strCardId from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ValidateCardId", ReplyAction="*")]
        SGM_SaleGas.SGM_Service.ValidateCardIdResponse ValidateCardId(SGM_SaleGas.SGM_Service.ValidateCardIdRequest request);
        
        // CODEGEN: Generating message contract since element name strCardId from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GasBuying", ReplyAction="*")]
        SGM_SaleGas.SGM_Service.GasBuyingResponse GasBuying(SGM_SaleGas.SGM_Service.GasBuyingRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ValidateGasStationLoginRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ValidateGasStationLogin", Namespace="http://tempuri.org/", Order=0)]
        public SGM_SaleGas.SGM_Service.ValidateGasStationLoginRequestBody Body;
        
        public ValidateGasStationLoginRequest() {
        }
        
        public ValidateGasStationLoginRequest(SGM_SaleGas.SGM_Service.ValidateGasStationLoginRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ValidateGasStationLoginRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string stGasStationID;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string stGasStationMacAddress;
        
        public ValidateGasStationLoginRequestBody() {
        }
        
        public ValidateGasStationLoginRequestBody(string stGasStationID, string stGasStationMacAddress) {
            this.stGasStationID = stGasStationID;
            this.stGasStationMacAddress = stGasStationMacAddress;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ValidateGasStationLoginResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ValidateGasStationLoginResponse", Namespace="http://tempuri.org/", Order=0)]
        public SGM_SaleGas.SGM_Service.ValidateGasStationLoginResponseBody Body;
        
        public ValidateGasStationLoginResponse() {
        }
        
        public ValidateGasStationLoginResponse(SGM_SaleGas.SGM_Service.ValidateGasStationLoginResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ValidateGasStationLoginResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string ValidateGasStationLoginResult;
        
        public ValidateGasStationLoginResponseBody() {
        }
        
        public ValidateGasStationLoginResponseBody(string ValidateGasStationLoginResult) {
            this.ValidateGasStationLoginResult = ValidateGasStationLoginResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ValidateCardIdRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ValidateCardId", Namespace="http://tempuri.org/", Order=0)]
        public SGM_SaleGas.SGM_Service.ValidateCardIdRequestBody Body;
        
        public ValidateCardIdRequest() {
        }
        
        public ValidateCardIdRequest(SGM_SaleGas.SGM_Service.ValidateCardIdRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ValidateCardIdRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string strCardId;
        
        public ValidateCardIdRequestBody() {
        }
        
        public ValidateCardIdRequestBody(string strCardId) {
            this.strCardId = strCardId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ValidateCardIdResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ValidateCardIdResponse", Namespace="http://tempuri.org/", Order=0)]
        public SGM_SaleGas.SGM_Service.ValidateCardIdResponseBody Body;
        
        public ValidateCardIdResponse() {
        }
        
        public ValidateCardIdResponse(SGM_SaleGas.SGM_Service.ValidateCardIdResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ValidateCardIdResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string ValidateCardIdResult;
        
        public ValidateCardIdResponseBody() {
        }
        
        public ValidateCardIdResponseBody(string ValidateCardIdResult) {
            this.ValidateCardIdResult = ValidateCardIdResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GasBuyingRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GasBuying", Namespace="http://tempuri.org/", Order=0)]
        public SGM_SaleGas.SGM_Service.GasBuyingRequestBody Body;
        
        public GasBuyingRequest() {
        }
        
        public GasBuyingRequest(SGM_SaleGas.SGM_Service.GasBuyingRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GasBuyingRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string strCardId;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public int money;
        
        public GasBuyingRequestBody() {
        }
        
        public GasBuyingRequestBody(string strCardId, int money) {
            this.strCardId = strCardId;
            this.money = money;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GasBuyingResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GasBuyingResponse", Namespace="http://tempuri.org/", Order=0)]
        public SGM_SaleGas.SGM_Service.GasBuyingResponseBody Body;
        
        public GasBuyingResponse() {
        }
        
        public GasBuyingResponse(SGM_SaleGas.SGM_Service.GasBuyingResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GasBuyingResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string GasBuyingResult;
        
        public GasBuyingResponseBody() {
        }
        
        public GasBuyingResponseBody(string GasBuyingResult) {
            this.GasBuyingResult = GasBuyingResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ServiceSoapChannel : SGM_SaleGas.SGM_Service.ServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServiceSoapClient : System.ServiceModel.ClientBase<SGM_SaleGas.SGM_Service.ServiceSoap>, SGM_SaleGas.SGM_Service.ServiceSoap {
        
        public ServiceSoapClient() {
        }
        
        public ServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SGM_SaleGas.SGM_Service.ValidateGasStationLoginResponse SGM_SaleGas.SGM_Service.ServiceSoap.ValidateGasStationLogin(SGM_SaleGas.SGM_Service.ValidateGasStationLoginRequest request) {
            return base.Channel.ValidateGasStationLogin(request);
        }
        
        public string ValidateGasStationLogin(string stGasStationID, string stGasStationMacAddress) {
            SGM_SaleGas.SGM_Service.ValidateGasStationLoginRequest inValue = new SGM_SaleGas.SGM_Service.ValidateGasStationLoginRequest();
            inValue.Body = new SGM_SaleGas.SGM_Service.ValidateGasStationLoginRequestBody();
            inValue.Body.stGasStationID = stGasStationID;
            inValue.Body.stGasStationMacAddress = stGasStationMacAddress;
            SGM_SaleGas.SGM_Service.ValidateGasStationLoginResponse retVal = ((SGM_SaleGas.SGM_Service.ServiceSoap)(this)).ValidateGasStationLogin(inValue);
            return retVal.Body.ValidateGasStationLoginResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SGM_SaleGas.SGM_Service.ValidateCardIdResponse SGM_SaleGas.SGM_Service.ServiceSoap.ValidateCardId(SGM_SaleGas.SGM_Service.ValidateCardIdRequest request) {
            return base.Channel.ValidateCardId(request);
        }
        
        public string ValidateCardId(string strCardId) {
            SGM_SaleGas.SGM_Service.ValidateCardIdRequest inValue = new SGM_SaleGas.SGM_Service.ValidateCardIdRequest();
            inValue.Body = new SGM_SaleGas.SGM_Service.ValidateCardIdRequestBody();
            inValue.Body.strCardId = strCardId;
            SGM_SaleGas.SGM_Service.ValidateCardIdResponse retVal = ((SGM_SaleGas.SGM_Service.ServiceSoap)(this)).ValidateCardId(inValue);
            return retVal.Body.ValidateCardIdResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SGM_SaleGas.SGM_Service.GasBuyingResponse SGM_SaleGas.SGM_Service.ServiceSoap.GasBuying(SGM_SaleGas.SGM_Service.GasBuyingRequest request) {
            return base.Channel.GasBuying(request);
        }
        
        public string GasBuying(string strCardId, int money) {
            SGM_SaleGas.SGM_Service.GasBuyingRequest inValue = new SGM_SaleGas.SGM_Service.GasBuyingRequest();
            inValue.Body = new SGM_SaleGas.SGM_Service.GasBuyingRequestBody();
            inValue.Body.strCardId = strCardId;
            inValue.Body.money = money;
            SGM_SaleGas.SGM_Service.GasBuyingResponse retVal = ((SGM_SaleGas.SGM_Service.ServiceSoap)(this)).GasBuying(inValue);
            return retVal.Body.GasBuyingResult;
        }
    }
}
